build: false
platform: x86
clone_folder: C:\projects\xisodev\slugify

cache:
  - '%APPDATA%\Composer'
  - '%LOCALAPPDATA%\Composer'
  - C:\tools\composer.phar -> .appveyor.yml
  - C:\tools\php -> .appveyor.yml

init:
  - SET PATH=C:\tools\php;%PATH%

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - IF NOT EXIST C:\tools\php (choco install --yes --allow-empty-checksums php --params '/InstallDir:C:\tools\php')
  - cd C:\tools\php
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo memory_limit=3G >> php.ini
  - IF NOT EXIST C:\tools\composer.phar (cd C:\tools && appveyor DownloadFile https://getcomposer.org/composer.phar)
  - cd %APPVEYOR_BUILD_FOLDER%
  - php C:\tools\composer.phar global show hirak/prestissimo --quiet || php C:\tools\composer.phar global require hirak/prestissimo --no-progress
  - php C:\tools\composer.phar update --no-ansi --no-interaction --no-progress --no-suggest --optimize-autoloader --prefer-stable

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php vendor\phpunit\phpunit\phpunit
